ingress:
  rules:
  - component:
      name: api
    match:
      path:
        prefix: /api
  - component:
      name: website
    cors:
      allow_origins:
      - prefix: https://internal.example-app.com
    match:
      path:
        prefix: /
name: application-test-app
region: fra1
services:
- environment_slug: go
  dockerfile_path: ./
  image: victoria68/test-application:latest
  http_port: 8080
  name: application-test-app-service
  source_dir: /
