version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17

    working_directory: ~/test-application

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            docker build -t test-application .

  push:
    docker:
      - image: cimg/go:1.17

    working_directory: ~/test-application

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Login To DockerHub
          command: |
            docker login --username="$dockerhub_user" --password="$dockerhub_password"

      - run:
          name: Push Docker image to DockerHub
          command: |
            docker tag test-application victoria68/test-application
            docker push victoria68/test-application


  deploy:
    docker:
      - image: cimg/go:1.17

    working_directory: ~/test-application

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install To DigitalOcean Command
          command: |
            curl -sL https://github.com/digitalocean/doctl/releases/download/v1.61.0/doctl-1.61.0-linux-amd64.tar.gz | tar -xzv
            sudo mv ./doctl /usr/local/bin
            doctl version

      - run:
          name: Authenticate with DigitalOcean
          command: |
            doctl auth init -t $digital_ocean_api_token

      - run:
          name: Deploy App to DigitalOcean
          command: |
            doctl apps create-deployment $(doctl apps list)


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - push:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
            - push
          filters:
            branches:
              only: master