version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17

    working_directory: ~/test-application

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            docker build -t test-application .

  deploy:
    docker:
      - image: cimg/go:1.17

    working_directory: ~/test-application

    steps:
      - checkout
      
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh

      - run:
          name: Log in to Heroku
          command: |
            echo "machine api.heroku.com" >> ~/.netrc
            echo "  login $HEROKU_EMAIL" >> ~/.netrc
            echo "  password $HEROKU_API_KEY" >> ~/.netrc
            chmod 600 ~/.netrc
            heroku container:login

      - run:
          name: Push Docker image to Heroku
          command: |
            docker tag test-application registry.heroku.com/test-application/web
            docker push registry.heroku.com/test-application/web

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master