version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17

    working_directory: ~/test-application

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            docker build -t test-application .

  deploy:
    docker:
      - image: cimg/go:1.17

    working_directory: ~/test-application

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Login To DockerHub
          command: |
            docker login --username="$dockerhub_user" --email="$dockerhub_email"

      - run:
          name: Push Docker image to DockerHub
          command: |
            docker tag test-application victoria68/test-application
            docker push victoria68/test-application

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master