version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17

    working_directory: ~/test-application

    steps:
      - checkout

      - run:
          name: Build Docker image
          command: |
            docker build -t test-application .

  deploy:
    docker:
      - image: cimg/go:1.17

    working_directory: ~/test-application

    steps:
      - checkout

      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh

      - run:
          name: Log in to Heroku
          command: |
            echo "$HEROKU_API_KEY" | docker login -u "_ --password-stdin registry.heroku.com"

      - run:
          name: Push Docker image to Heroku
          command: |
            docker tag test-application registry.heroku.com/victoria/web
            docker push registry.heroku.com/victoria/web

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master